# Generated by Django 5.1.3 on 2024-11-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_category_name_alter_eventcategory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="eventspeaker",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventspeaker",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.speaker",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
