# Generated by Django 5.1.3 on 2024-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='speakers', to='events.speaker'),
        ),
        migrations.DeleteModel(
            name='EventSpeaker',
        ),
    ]
