# Generated by Django 5.1.3 on 2024-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_speakers_delete_eventspeaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="events.category"
            ),
        ),
        migrations.DeleteModel(
            name="EventCategory",
        ),
    ]
